# 
# In Host :
# sudo docker-compose -f docker-compose-dev.yml up
#
#
# To go in docker shell: 
# in Linux: sudo docker exec -it decouverto_website_website_1 sh
# in Mac: sudo docker exec -it decouverto-website-website-1 sh
#
# In Docker : 
# npm start

version: '3'
services:
  mongo:
    image: mongo:4.4
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
  website: 
    image: cedced19/decouverto-website
    tty: true
    command: sh -c "tail -f /dev/null"
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:8000
    volumes:
      - .:/usr/src/app 
    depends_on:
      mongo:
        condition: service_healthy
